# Generated by Django 2.2.28 on 2023-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230425_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dgzdfg',
        ),
        migrations.AddField(
            model_name='user',
            name='jhsddfdsh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
