# Generated by Django 2.2.28 on 2023-04-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230425_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hjgshjsd',
        ),
        migrations.AddField(
            model_name='user',
            name='ghfhgf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
